# -*- coding: utf-8 -*-
"""pratikum01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_bOPrZwZ-Ho4ed9i2swn_xD7FfPHN4Ty
"""



import pandas as pd
path="/content/drive/MyDrive/Colab Notebooks/dataanime.csv"
dataset=pd.read_csv(path)
dataset

dataset.head()

dataset.shape

dataset.isnull().sum()

dataset.max()

dataset.min()

dataset.describe()

dataset.describe().loc['max','Score']

dataset.describe()['Members']['max']

data=dataset.dropna()

data.shape

dataset.dropna(axis=0,subset=['Score','Members'],inplace=True)

data.shape

#Memilih data target prediksi
y=data['Members']
y

#Memilih Fitur
Fitur=['Title','Score']
X=data[Fitur]
X